### ISSUE TITLE
Getting error on plugin page after installation of simple podcasting plugin

### ISSUE THREAD

**Issue by sudip-md** [10up/simple-podcasting#138]
### Describe the bug

Getting error on plugin page after installation of simple podcasting plugin.
 Wordpress version - 5.9 RC_1
Plugin Version - 1.2.1
Server - Nginx
PHP Version - 7.3.5

### Steps to Reproduce

1. Install plugin via git 
2. run command `npm install && npm run build`
3. Go to Admin -> Plugins

### Screenshots, screen recording, code snippet

Screenshot - https://www.screencast.com/t/H9GxvLWxTZ

### Environment information

Device - Macbook
Os version -12.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankitguptaindia** [comment]
Hello @sudip-10up Thanks for sharing this feedback. 
Would like to add some feedback related to reporting issues/bugs in OSS project. Please follow the same instructions on all upcoming issues.

**Describe the bug Section -** 

Please also add error details in the description section as a TEXT so we can search and find results for similar issues when searching in the whole Git repo.

**Screenshots, screen recording Section -** 

Would be helpful if you upload image/video direct on Github via 'Atteching file' options. Because the services we are using to record screens, screenshots like Techsmith, Imgur are third-party services and maybe they remove/delete these files after some interval of time.  

**Environment /WordPress information Section-**
 
Please add your all information related to WP, server, etc in this section together and can also use Site Health Info from WP setting. 
Other details will be helpful here like SSL status, Active themes/plugins etc as engineers maybe start working on this after a long time so that related info will be helpful.

And again Thanks for your help here. :)

**Comment by Sidsector9** [comment]
@sudip-10up, the plugin doesn't seem to be the cause of this error. Most likely the response from `api.wordpress.org` was evaluated to an error. A page reload should probably remove the error.

To confirm I've tested `develop` and the WP repo versions on WP5.9-RC1 and is working correctly.

**Comment by sudip-md** [comment]
Thanks for the update. @Sidsector9 . Now it is working fine
