### ISSUE TITLE
Add Listening Time Block

### ISSUE THREAD

**Issue by vikrampm1** [10up/simple-podcasting#229]
More context here: https://github.com/10up/simple-podcasting/pull/214

**Comment by jeffpaul** [comment]
Noting that there's a Time to Read Block in core that we can mimic for this Time to Listen Block: https://wordpress.com/support/wordpress-editor/blocks/time-to-read-block/

**Comment by jeffpaul** [comment]
In chatting with @cedarstay, one option discussed was instead of crafting this as its own block would be to add a toggle to the podcast block to render this info around that block.  See #191 for potential designs for how that could look; options there being rendering above or below the audio player as well as having the label be `Duration`, `Runtime`, `Time to Listen`, or some other sensible copy.
