### ISSUE TITLE
Gutenberg: audio player does not work in block

### ISSUE THREAD

**Issue by helen** [10up/simple-podcasting#46]
In the podcasting block, the player can be interacted with but does not actually seem to load or play the file, whether external URL or from the media library. The core audio block player can't even be interacted with, at least in my setup. This probably needs some more testing across browsers, etc.

**Comment by helen** [comment]
Hmmm :( https://github.com/WordPress/gutenberg/issues/9252

**Comment by ryanwelcher** [comment]
@helen - I've been testing this and I believe this is a bug in the plugin rather than an issue with GB. I was able to get it to play in the admin using the following steps:

1. Create a new post with a block
2. Select an item from the media library
3. Publish
4. Edit the block and press the Use URL button
5. Publish and refresh the page.

I'm digging into the why, but I think the src props is not getting set until we click the useURL button.

The screenshot belows show the state after adding a .mp3 from the Media Library
<img width="1040" alt="missing prop" src="https://user-images.githubusercontent.com/1259027/47739684-49e26880-dc4c-11e8-86bd-69cfb82265ab.png">

This one is after I followed the steps above
<img width="1067" alt="after-steps" src="https://user-images.githubusercontent.com/1259027/47739778-83b36f00-dc4c-11e8-9385-62c004f256d0.png">
