### ISSUE TITLE
Remove Edit Icon in Block

### ISSUE THREAD

**Issue by turtlepod** [10up/simple-podcasting#61]
It's confusing because it's simply remove the podcast and no way to add it back. Maybe change it to "clear" icon.

**Video**
https://drive.google.com/file/d/1azwV3Oa5cXVaXAqzQyA1bbrcOVFdxRqU/view?usp=sharing

**Comment by helen** [comment]
I think you may be testing `master` here because there should be a URL field, which would be editable. It also allows you to select a different podcast. I do think there needs to be a way to "cancel" out of editing mode though, since as you're seeing here there's no way to get back to just keeping the current selection. Will open a new issue to explore that.
